In [1]:
import pandas as pd

# Load data

In [2]:
# DATASET = "prwp_batch1"
# DATASET = "prwp_batch2"
DATASET = "refugee_batch1"

df = pd.read_json(f"data/results_{DATASET}.jsonl", lines=True)
df

,snapshot_id,image_path,source_label,llm_output,raw_output,usage,cost,error
0,112_IDAR2016-0221-PAD-09012016_table_007.png,data/refugee_batch1/112_IDAR2016-0221-PAD-0901...,Refugee,{'visible_text_label': 'Consultancy Assignment...,"```json\n{\n ""visible_text_label"": ""Consultan...","{'input_tokens': 26304, 'input_tokens_details'...","{'input_tokens': 26304, 'output_tokens': 121, ...",NaN
1,056_Niger-COVID-19-Emergency-Response-Project_...,data/refugee_batch1/056_Niger-COVID-19-Emergen...,Refugee,"{'visible_text_label': 'Figure 1: Countries, t...","{\n ""visible_text_label"": ""Figure 1: Countrie...","{'input_tokens': 37607, 'input_tokens_details'...","{'input_tokens': 37607, 'output_tokens': 142, ...",NaN
2,194_multi-page_figure_000.png,data/refugee_batch1/194_multi-page_figure_000.png,Refugee,{'visible_text_label': 'Annex 10: Country at a...,"```json\n{\n ""visible_text_label"": ""Annex 10:...","{'input_tokens': 37681, 'input_tokens_details'...","{'input_tokens': 37681, 'output_tokens': 162, ...",NaN
3,069_Pakistan-Strengthening-Institutions-for-Re...,data/refugee_batch1/069_Pakistan-Strengthening...,Refugee,{'visible_text_label': 'Project Development Ob...,"{\n ""visible_text_label"": ""Project Developmen...","{'input_tokens': 49016, 'input_tokens_details'...","{'input_tokens': 49016, 'output_tokens': 118, ...",NaN
4,202_multi0page_table_007.png,data/refugee_batch1/202_multi0page_table_007.png,Refugee,{'visible_text_label': 'Annex 6 El Nino Emerge...,"```json\n{\n ""visible_text_label"": ""Annex 6\n...","{'input_tokens': 37654, 'input_tokens_details'...","{'input_tokens': 37654, 'output_tokens': 141, ...",NaN
...,...,...,...,...,...,...,...,...
494,055_Chad-COVID-19-Response-Project_table_000.png,data/refugee_batch1/055_Chad-COVID-19-Response...,Refugee,{'visible_text_label': 'Proposed Project Devel...,"{\n ""visible_text_label"": ""Proposed Project D...","{'input_tokens': 49029, 'input_tokens_details'...","{'input_tokens': 49029, 'output_tokens': 134, ...",NaN
495,195_multi-page_table_007.png,data/refugee_batch1/195_multi-page_table_007.png,Refugee,{'visible_text_label': 'Estimated Schedule (mo...,"{\n ""visible_text_label"": ""Estimated Schedule...","{'input_tokens': 37664, 'input_tokens_details'...","{'input_tokens': 37664, 'output_tokens': 120, ...",NaN
496,014_BOSIB1dda1d49e0221807413cf06ea9ae3f_table_...,../../../data/snapshots/refugee_batch1/014_BOS...,Refugee,"{'visible_text_label': 'Components', 'data_mod...","```json\n{\n ""visible_text_label"": ""Component...","{'input_tokens': 48966, 'input_tokens_details'...","{'input_tokens': 48966, 'output_tokens': 108, ...",NaN
497,197_multi-page_table_001.png,../../../data/snapshots/refugee_batch1/197_mul...,Refugee,{'visible_text_label': 'Annex 3 Estimated Proj...,"{\n ""visible_text_label"": ""Annex 3 Estimated ...","{'input_tokens': 48968, 'input_tokens_details'...","{'input_tokens': 48968, 'output_tokens': 116, ...",NaN
498,004_BOSIB-87c444de-4797-4bf9-b654-4932a7fb0112...,../../../data/snapshots/refugee_batch1/004_BOS...,Refugee,{'visible_text_label': 'ANNEX 3: Geographical ...,"{\n ""visible_text_label"": ""ANNEX 3: Geographi...","{'input_tokens': 26097, 'input_tokens_details'...","{'input_tokens': 26097, 'output_tokens': 117, ...",NaN

# Check for errors

In [3]:
df[df["error"].notna()]

Empty DataFrame
Columns: [snapshot_id, image_path, source_label, llm_output, raw_output, usage, cost, error]
Index: []

# Export short description

In [4]:
df = df.join(pd.json_normalize(df['llm_output'])).drop(columns=['llm_output', "raw_output", "usage", "error"])
df

,snapshot_id,image_path,source_label,cost,visible_text_label,data_modality,topic_domain,population,geographic_scope,temporal_aspect,measurement_units,short_description
0,112_IDAR2016-0221-PAD-09012016_table_007.png,data/refugee_batch1/112_IDAR2016-0221-PAD-0901...,Refugee,"{'input_tokens': 26304, 'output_tokens': 121, ...",Consultancy Assignments with Selection Methods...,administrative counts,urban development,unclear,West Bank and Gaza,unclear,USD ($000),The table lists various consultancy assignment...
1,056_Niger-COVID-19-Emergency-Response-Project_...,data/refugee_batch1/056_Niger-COVID-19-Emergen...,Refugee,"{'input_tokens': 37607, 'output_tokens': 142, ...","Figure 1: Countries, territories or areas with...",geospatial distribution,health,unclear,global,specific date (24 March 2020),counts,The figure displays a world map indicating cou...
2,194_multi-page_figure_000.png,data/refugee_batch1/194_multi-page_figure_000.png,Refugee,"{'input_tokens': 37681, 'output_tokens': 162, ...",Annex 10: Country at a Glance\nWEST BANK AND G...,key economic ratios and demographic indicators,"poverty and social conditions, economic develo...",general population,West Bank and Gaza,single year (1997),"counts, percentages, USD billions",The snapshot reports on various socio-economic...
3,069_Pakistan-Strengthening-Institutions-for-Re...,data/refugee_batch1/069_Pakistan-Strengthening...,Refugee,"{'input_tokens': 49016, 'output_tokens': 118, ...",Project Development Objective Indicators,performance indicators,refugee management,refugees,Pakistan,unclear,"percentages, counts",The table outlines project development objecti...
4,202_multi0page_table_007.png,data/refugee_batch1/202_multi0page_table_007.png,Refugee,"{'input_tokens': 37654, 'output_tokens': 141, ...",Annex 6\nEl Nino Emergency Road Repair Project...,administrative counts,infrastructure rehabilitation,unclear,Uganda,specific dates and planned timelines,"US dollars, months, specific dates",The snapshot contains a project budget and sch...
...,...,...,...,...,...,...,...,...,...,...,...,...
494,055_Chad-COVID-19-Response-Project_table_000.png,data/refugee_batch1/055_Chad-COVID-19-Response...,Refugee,"{'input_tokens': 49029, 'output_tokens': 134, ...",Proposed Project Development Objective(s)\nTo ...,budget allocation,health,unclear,Chad,single year,millions of US dollars,The table lists the components of the COVID-19...
495,195_multi-page_table_007.png,data/refugee_batch1/195_multi-page_table_007.png,Refugee,"{'input_tokens': 37664, 'output_tokens': 120, ...",Estimated Schedule (month/year),budget allocation,health,unclear,Jordan,project timeline,US$ million,The table outlines costs associated with vario...
496,014_BOSIB1dda1d49e0221807413cf06ea9ae3f_table_...,../../../data/snapshots/refugee_batch1/014_BOS...,Refugee,"{'input_tokens': 48966, 'output_tokens': 108, ...",Components,budget allocation,economic development,"Micro, Small and Medium Enterprises (MSMEs)",Burundi,unclear,US dollars,The table lists the components of the Jobs and...
497,197_multi-page_table_001.png,../../../data/snapshots/refugee_batch1/197_mul...,Refugee,"{'input_tokens': 48968, 'output_tokens': 116, ...",Annex 3 Estimated Project Costs,budget estimates,community development,returnees and vulnerable groups,Rwanda,unclear,US$ million,The table presents estimated project costs for...
498,004_BOSIB-87c444de-4797-4bf9-b654-4932a7fb0112...,../../../data/snapshots/refugee_batch1/004_BOS...,Refugee,"{'input_tokens': 26097, 'output_tokens': 117, ...",ANNEX 3: Geographical distribution of the refu...,geographical distribution,displacement,refugees and asylum seekers,Djibouti,unclear,counts,The map shows the distribution of refugees and...

In [5]:
df2 = df.set_index("snapshot_id")["short_description"].copy()
df2.to_csv(f"data/shortdesc_{DATASET}.csv")